### PR TITLE
Update README.md to contain proposal spec link

### PR DESCRIPTION
**Pull request by assuncaocharles**

### CODE REVIEW

**Comment by ljharb** [comment]
The link is already in the right-hand column of the main repo page.

**Comment by jridgewell** [comment]
The GitHub UI already displays one in the top right
Screen Shot 2021-11-26 at 8 10 54 PM

**Comment by assuncaocharles** [comment]
Ok fair enough, I just suggested as I have seen some other proposals with it and seemed better for discovery

**Comment by jridgewell** [comment]
I can understand, but I'm not sure the spec text is what people want when they think of accessible. 😄 

I think the default GitHub UI is sufficient here, and we can add more links when someone publishes explainers or tutorials.

**Pull request closed without merging**
