### PR TITLE
Update abstract op so early return is obvious

### PR DESCRIPTION
**Pull request by jridgewell**

### CODE REVIEW

**Comment by ljharb** [comment]
Is there any chance there could be more than one matching group in groups? The previous algorithm selected the last one, this selects the first. I suspect it doesn’t matter here but wanted to call it out.

**Comment by jridgewell** [comment]
Nope, it's guaranteed to be unique. But that wasn't obvious from the code, which is why I thought to change it. Since you made it an abstract op, the early return is easy (I couldn't find a similar "break" op in a "for each" loop).

**Comment by ljharb** [comment]
Maybe we should add an assertion before the loop - something that ensures that any [[Key]] in the groups list only appears once?

**Comment by jridgewell** [comment]
Do you know how we would phrase that? Is it ok to hand wave and say "at most one record will match SameValueZero"?

**Comment by jridgewell** [comment]
Alternatively, I could switch back and `Assert: _group_ is ~empty~`.

**Comment by ljharb** [comment]
I think phrasing like that would work; give me a bit and I’ll make a PR.

**Comment by ljharb** [comment]
Found a couple useful precedents; filed #23

**Pull request merged**
